site_name: Base Documental
docs_dir: docs/

repo_name: 'Taligent-UNID/document-base'
repo_url: 'https://github.com/Taligent-UNID/document-base'

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true